branch-defaults:
  master:
    environment: W210CrimeDataLoad-env
environment-defaults:
  W210CrimeDataLoad-env:
    branch: null
    repository: null
global:
  application_name: w210_crime_data_load
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
